name: Deploy EC2 with Terraform

# Define when the workflow should run
on:
  push:
    branches:
      - master  # Trigger when code is pushed to the main branch
  pull_request:
    branches:
      - master  # Trigger when a PR is merged into the main branch

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest  # GitHub's Ubuntu runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var "key_name=${{ secrets.AWS_KEY_NAME }}"
        
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 5: Apply the Terraform plan
      - name: Terraform Apply
        run: terraform apply -var "key_name=${{ secrets.AWS_KEY_NAME }}" -auto-approve
        
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
